// services/search.ts
import { generateEmbedding } from "./ollamaEmbedder";
import * as lancedb from "@lancedb/lancedb";

/**
 * Performs a high-performance, deduplicated multi-query search across the vector database.
 * This approach ensures a broader context retrieval by searching for multiple semantic variations.
 * * @param queries - An array of optimized search terms generated by the LLM.
 * @param topK - The number of top results to retrieve per individual query.
 * @returns A promise resolving to an array of unique, relevant code/text chunks.
 */
export async function searchInEmbeddings(
  queries: string[],
  topK = 3,
): Promise<string[]> {
  const dbPath = "src/data/";
  const db = await lancedb.connect(dbPath);

  // Attempt to open the target table
  const table = await db.openTable("testdata");

  if (!table) {
    throw new Error(
      "Vector table 'testdata' not found. Please ensure indexing is complete.",
    );
  }

  // Execute all searches in parallel to minimize latency, especially when using local LLMs
  const searchPromises = queries.map(async (query) => {
    // 1. Generate the vector representation (embedding) for the specific sub-query
    const queryEmbedding = await generateEmbedding(query);

    if (!queryEmbedding) {
      console.warn(`⚠️ Failed to generate embedding for query: "${query}"`);
      return [];
    }

    // 2. Perform the vector similarity search in LanceDB
    return await table.search(queryEmbedding).limit(topK).toArray();
  });

  // Flatten the array of arrays into a single result pool
  const allResultsRaw = await Promise.all(searchPromises);
  const flatResults = allResultsRaw.flat();

  /**
   * DEDUPLICATION LOGIC:
   * Since different queries might point to the same document section,
   * we filter based on a combination of file path and text content.
   */
  const uniqueResults = flatResults.filter(
    (item, index, self) =>
      index ===
      self.findIndex((t) => t.path === item.path && t.text === item.text),
  );

  // Logging for debugging and observability
  if (uniqueResults.length === 0) {
    console.log(
      "⚠️ Search completed: No relevant context found across all queries.",
    );
  } else {
    console.log(
      `🔍 Search completed: Retrieved ${uniqueResults.length} unique chunks.`,
    );
  }

  return uniqueResults;
}
